package view;

/*
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chuqu
 */
import model.QLSVModel;
import model.ThiSinh;
import model.Tinh;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QLSVView extends javax.swing.JFrame {

    /**
     * Creates new form QLSVView
     *
     */
    private QLSVModel qlsvModel;
    ActionEvent evt;

    public QLSVView() {
        qlsvModel = new QLSVModel();
        initComponents();
        this.setVisible(true);
        JOptionPane.showMessageDialog(this ,"Chào mừng bạn");
        jComboBoxQueQuan1ActionPerformed(evt);
        jComboBoxQueQuanActionPerformed(evt);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelGioiTinh = new javax.swing.JLabel();
        jLabelMaThiSinh = new javax.swing.JLabel();
        jButtonTim = new javax.swing.JButton();
        jComboBoxQueQuan = new javax.swing.JComboBox<>();
        jTextFieldMaThiSinh2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabeThongTinThiSinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelDanhSachThiSinh1 = new javax.swing.JLabel();
        jLabelQueQuan1 = new javax.swing.JLabel();
        jLabelHoVaTen = new javax.swing.JLabel();
        jLabelQueQuan2 = new javax.swing.JLabel();
        jLabelNgaySinh = new javax.swing.JLabel();
        jTextFieldMaThiSinh1 = new javax.swing.JTextField();
        jTextFieldMon1 = new javax.swing.JTextField();
        jTextFieldNgaySinh = new javax.swing.JTextField();
        jLabelMaThiSinh3 = new javax.swing.JLabel();
        jRadioButtonGioiTinhNu = new javax.swing.JRadioButton();
        jRadioButtonGioiTinhNam = new javax.swing.JRadioButton();
        jLabelMon2 = new javax.swing.JLabel();
        jTextFieldHoVaTen1 = new javax.swing.JTextField();
        jLabelMon1 = new javax.swing.JLabel();
        jLabelMon3 = new javax.swing.JLabel();
        jTextFieldMon3 = new javax.swing.JTextField();
        jTextFieldMon2 = new javax.swing.JTextField();
        jComboBoxQueQuan1 = new javax.swing.JComboBox<>();
        jButtonThem = new javax.swing.JButton();
        jButtonCapNhat = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonLuu = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonHuyBo = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuClose = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        // Để cho nam nữ chỉ được chọn 1
        jButtonGroupGioiTinh = new javax.swing.ButtonGroup();
        jButtonGroupGioiTinh.add(jRadioButtonGioiTinhNam);
        jButtonGroupGioiTinh.add(jRadioButtonGioiTinhNu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGioiTinh.setText("Giới tính");

        jLabelMaThiSinh.setText("Mã thí sinh");

        jButtonTim.setText("Tìm");
        jButtonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimActionPerformed(evt);
            }
        });

        jComboBoxQueQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBoxQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jComboBoxQueQuanActionPerformed(evt);
            }
        });

        jTextFieldMaThiSinh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaThiSinh2ActionPerformed(evt);
            }
        });

        jLabeThongTinThiSinh.setText("Thông tin thí sinh");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                        "STT","Mã Thí Sinh", "Họ tên " ,"Quê Quán","Ngày sinh" ,"Giới tính", "Điểm 1", "Điểm 2", "Điểm 3"
                }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelDanhSachThiSinh1.setText("Danh sách thí sinh");

        jLabelQueQuan1.setText("Quê Quán");

        jLabelHoVaTen.setText("Họ và Tên");

        jLabelQueQuan2.setText("Quê Quán");

        jLabelNgaySinh.setText("Ngày Sinh");

        jTextFieldMaThiSinh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaThiSinh1ActionPerformed(evt);
            }
        });

        jTextFieldMon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMon1ActionPerformed(evt);
            }
        });

        jTextFieldNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNgaySinhActionPerformed(evt);
            }
        });

        jLabelMaThiSinh3.setText("Mã thí sinh");

        jRadioButtonGioiTinhNu.setText("Nữ");
        jRadioButtonGioiTinhNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGioiTinhNuActionPerformed(evt);
            }
        });

        jRadioButtonGioiTinhNam.setText("Nam");

        jLabelMon2.setText("Môn 2");

        jTextFieldHoVaTen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoVaTen1ActionPerformed(evt);
            }
        });

        jLabelMon1.setText("Môn 1");

        jLabelMon3.setText("Môn 3");

        jTextFieldMon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMon3ActionPerformed(evt);
            }
        });

        jTextFieldMon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMon2ActionPerformed(evt);
            }
        });

        jComboBoxQueQuan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        jComboBoxQueQuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jComboBoxQueQuan1ActionPerformed(evt);
            }
        });

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonCapNhat.setText("Cập nhật");
        jButtonCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapNhatActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonLuu.setText("Lưu");
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        jButtonHuyBo.setText("Hủy bỏ");
        jButtonHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyBoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabelQueQuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jComboBoxQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(63, 63, 63)
                                                                .addComponent(jLabelMaThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jTextFieldMaThiSinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jButtonTim, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabelDanhSachThiSinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                                                .addComponent(jLabelMaThiSinh3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jTextFieldMaThiSinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(79, 79, 79)
                                                                                                .addComponent(jLabelGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabelHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(jTextFieldHoVaTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabelNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(jTextFieldNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabelQueQuan2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(jComboBoxQueQuan1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                .addGap(79, 79, 79)
                                                                                                                .addComponent(jLabelMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                        .addComponent(jLabelMon2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                        .addComponent(jLabelMon3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(18, 18, 18)))))
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addComponent(jRadioButtonGioiTinhNam)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jRadioButtonGioiTinhNu))
                                                                                        .addComponent(jTextFieldMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jTextFieldMon3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jTextFieldMon2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(jLabeThongTinThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(14, 14, 14)
                                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(22, 22, 22)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jButtonCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButtonHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelMaThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonTim)
                                        .addComponent(jLabelQueQuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldMaThiSinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDanhSachThiSinh1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabeThongTinThiSinh)
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextFieldMaThiSinh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelGioiTinh)
                                                        .addComponent(jLabelMaThiSinh3)
                                                        .addComponent(jRadioButtonGioiTinhNu)
                                                        .addComponent(jRadioButtonGioiTinhNam))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelHoVaTen)
                                                        .addComponent(jTextFieldMon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelMon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldHoVaTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelQueQuan2)
                                                        .addComponent(jLabelMon2)
                                                        .addComponent(jTextFieldMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBoxQueQuan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelNgaySinh)
                                                        .addComponent(jTextFieldNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelMon3)
                                                        .addComponent(jTextFieldMon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addComponent(jButtonHuyBo))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButtonThem)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButtonXoa)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButtonCapNhat)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButtonLuu)
                                                        .addGap(35, 35, 35))
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabelMaThiSinh.getAccessibleContext().setAccessibleName("Quê Quán");

        menuFile.setText("File");

        menuOpen.setBackground(new java.awt.Color(204, 255, 204));
        menuOpen.setForeground(new java.awt.Color(255, 51, 51));
        menuOpen.setText("Open");
        menuFile.add(menuOpen);

        menuClose.setBackground(new java.awt.Color(204, 255, 204));
        menuClose.setForeground(new java.awt.Color(255, 51, 51));
        menuClose.setText("Close");
        menuFile.add(menuClose);

        separator.setBackground(new java.awt.Color(204, 255, 204));
        separator.setForeground(new java.awt.Color(255, 51, 51));
        menuFile.add(separator);

        menuExit.setBackground(new java.awt.Color(204, 255, 204));
        menuExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuExit.setForeground(new java.awt.Color(255, 51, 51));
        menuExit.setText("Exit");
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        jMenu2.setText("About");

        jMenuItem2.setBackground(new java.awt.Color(204, 255, 204));
        jMenuItem2.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem2.setText("About me");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonTimActionPerformed(java.awt.event.ActionEvent evt) {

        // TODO add your handling code here:
        int queQuan = jComboBoxQueQuan.getSelectedIndex();
        Tinh tinh = Tinh.getTinhById(queQuan - 1);
        for (int i = 0; i < qlsvModel.size(); i++) {
            List<ThiSinh> list = new ArrayList<>();

            if(tinh.getTenTinh().equals(qlsvModel.getDsThiSinh().get(i).getQueQuan())){
                list.add(qlsvModel.getDsThiSinh().get(i));
                ResultSearch search = new ResultSearch();
                search.setThiSinh(list);
               search.display();
               search.setVisible(true);
            }
        }

    }

    private void jComboBoxQueQuanActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ArrayList<Tinh> list = Tinh.getDSTinh();
        jComboBoxQueQuan.addItem("");
        for (int i = 0; i < list.size(); i++) {
            jComboBoxQueQuan.addItem(list.get(i).getTenTinh());
        }

    }

    private void jTextFieldMaThiSinh2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldMaThiSinh1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldMon1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jRadioButtonGioiTinhNuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldHoVaTen1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldMon3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldMon2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxQueQuan1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ArrayList<Tinh> list = Tinh.getDSTinh();
        jComboBoxQueQuan1.addItem("");
        for (int i = 0; i < list.size(); i++) {
            jComboBoxQueQuan1.addItem(list.get(i).getTenTinh());
        }
    }

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int maThiSinh = Integer.valueOf(jTextFieldMaThiSinh2.getText());
            String hoVaTen = jTextFieldHoVaTen1.getText();
            int queQuan = jComboBoxQueQuan1.getSelectedIndex();
            Tinh tinh = Tinh.getTinhById(queQuan - 1);
            String date = jTextFieldNgaySinh.getText();
            SimpleDateFormat sdfInput = new SimpleDateFormat("dd/MM/yyyy");
            Date ngaySinhDate = sdfInput.parse(date);

            boolean gioiTinh = true;

            if (jRadioButtonGioiTinhNam.isSelected()) {
                gioiTinh = true;
            } else if (jRadioButtonGioiTinhNu.isSelected()) {
                gioiTinh = false;
            }

            double mon1 = Double.valueOf(jTextFieldMon1.getText());
            double mon2 = Double.valueOf(jTextFieldMon2.getText());
            double mon3 = Double.valueOf(jTextFieldMon3.getText());

            // Kiểm tra dữ liệu trước khi tạo đối tượng ThiSinh
            if (mon1 < 0 || mon2 < 0 || mon3 < 0) {
                throw new IllegalArgumentException("Điểm không được âm");
            }

            ThiSinh thiSinh = new ThiSinh(maThiSinh, hoVaTen, tinh, ngaySinhDate, gioiTinh, mon1, mon2, mon3);
            int sizeBefore = qlsvModel.size();
            qlsvModel.insert(thiSinh);
            int sizeAfter = qlsvModel.size();

            if (sizeBefore != sizeAfter) {
                addTable();
                xoaForm();
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nhập sai định dạng số của điểm .");
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void xoaForm(){
        jTextFieldMaThiSinh2.setText("");
        jTextFieldHoVaTen1.setText("");
        jComboBoxQueQuan1.setSelectedIndex(-1);
        jTextFieldNgaySinh.setText("");
        jTextFieldMon1.setText("");
        jTextFieldMon2.setText("");
        jTextFieldMon3.setText("");
        jButtonGroupGioiTinh.clearSelection();

    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int selectionRow = jTable1.getSelectedRow();
        if(selectionRow >= 0){
            String studentID = jTable1.getValueAt(selectionRow ,1)+"";
            for (int i = 0; i < qlsvModel.size() ;i++) {
                ThiSinh thiSinh = qlsvModel.getDsThiSinh().get(i);
                if(studentID.equals(thiSinh.getMaThiSinh()+"")){
                    jTextFieldMaThiSinh2.setText(thiSinh.getMaThiSinh()+"");
                    jTextFieldHoVaTen1.setText(thiSinh.getTenSinhVien()+"");
                    jComboBoxQueQuan1.setSelectedItem(thiSinh.getQueQuan()+"");
                    Date date = thiSinh.getNgaySinh();
                    SimpleDateFormat sdfOutput = new SimpleDateFormat("dd/MM/yyyy");
                    String ngaySinhString = sdfOutput.format(date);
                    jTextFieldNgaySinh.setText(ngaySinhString);



                    if (thiSinh.getGioiTinh()) {
                        jRadioButtonGioiTinhNam.setSelected(true);
                    } else {
                        jRadioButtonGioiTinhNu.setSelected(true);
                    }
                    jTextFieldMon1.setText(thiSinh.getDiemMon1() +"");
                    jTextFieldMon2.setText(thiSinh.getDiemMon2() +"");
                    jTextFieldMon3.setText(thiSinh.getDiemMon3() +"");
                    break;
                }
            }
        }

    }

    private void jButtonCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        for (int i = 0; i < qlsvModel.size() ;i++) {
            ThiSinh thiSinh = qlsvModel.getDsThiSinh().get(i);
            if(thiSinh.getMaThiSinh() == Integer.valueOf(jTextFieldMaThiSinh2.getText())){
                thiSinh.setTenSinhVien(jTextFieldHoVaTen1.getText()+"");
                int queQuan = jComboBoxQueQuan1.getSelectedIndex();
                Tinh tinh = Tinh.getTinhById(queQuan - 1);
                thiSinh.setQueQuan(tinh);
                String date = jTextFieldNgaySinh.getText();
                SimpleDateFormat sdfInput = new SimpleDateFormat("dd/MM/yyyy");
                Date ngaySinhDate = null;
                try {
                    ngaySinhDate = sdfInput.parse(date);
                } catch (ParseException e) {
                    // Handle the parsing error, e.g., show a message to the user
                    e.printStackTrace(); // print the stack trace for debugging
                }

                boolean gioiTinh = true;

                if (jRadioButtonGioiTinhNam.isSelected()) {
                    gioiTinh = true;
                } else if (jRadioButtonGioiTinhNu.isSelected()) {
                    gioiTinh = false;

                }
                thiSinh.setNgaySinh(ngaySinhDate);
                thiSinh.setGioiTinh(gioiTinh);
                thiSinh.setDiemMon1(Double.valueOf(jTextFieldMon1.getText()));
                thiSinh.setDiemMon2(Double.valueOf(jTextFieldMon2.getText()));
                thiSinh.setDiemMon3(Double.valueOf(jTextFieldMon3.getText()));
            }

        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        model.setValueAt(jTextFieldHoVaTen1.getText()+"" ,row ,2);
        int queQuan = jComboBoxQueQuan1.getSelectedIndex();
        Tinh tinh = Tinh.getTinhById(queQuan - 1);
        model.setValueAt(tinh.getTenTinh()+"",row ,3);
        model.setValueAt(jTextFieldNgaySinh.getText()+"" ,row ,4);
        boolean gioiTinhNam = jRadioButtonGioiTinhNam.isSelected();
        String gioiTinh = gioiTinhNam ? "Nam" : "Nữ";
        model.setValueAt(gioiTinh, row, 5);
        model.setValueAt(jTextFieldMon1.getText()+"" ,row ,6);
        model.setValueAt(jTextFieldMon2.getText()+"" ,row ,7);
        model.setValueAt(jTextFieldMon3.getText()+"" ,row ,8);
    }
    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        DefaultTableModel modelTable = (DefaultTableModel) jTable1.getModel();
        int i_row = jTable1.getSelectedRow();
        int luaChon = JOptionPane.showConfirmDialog(this ,"Bạn có chắc chắn muốn xóa không ?");
        if(luaChon == JOptionPane.YES_OPTION){
            modelTable.removeRow(i_row);
            int maThiSinh = Integer.valueOf(jTextFieldMaThiSinh2.getText());
            String hoVaTen = jTextFieldHoVaTen1.getText();
            int queQuan = jComboBoxQueQuan1.getSelectedIndex();
            Tinh tinh = Tinh.getTinhById(queQuan - 1);
            String date = jTextFieldNgaySinh.getText();
            SimpleDateFormat sdfInput = new SimpleDateFormat("dd/MM/yyyy");
            Date ngaySinhDate = null;
            try {
                ngaySinhDate = sdfInput.parse(date);
            } catch (ParseException e) {
                // Handle the parsing error, e.g., show a message to the user
                e.printStackTrace(); // print the stack trace for debugging
            }

            boolean gioiTinh = true;

            if (jRadioButtonGioiTinhNam.isSelected()) {
                gioiTinh = true;
            } else if (jRadioButtonGioiTinhNu.isSelected()) {
                gioiTinh = false;
            }

            double mon1 = Double.valueOf(jTextFieldMon1.getText());
            double mon2 = Double.valueOf(jTextFieldMon2.getText());
            double mon3 = Double.valueOf(jTextFieldMon3.getText());

            // Kiểm tra dữ liệu trước khi tạo đối tượng ThiSinh
            if (mon1 < 0 || mon2 < 0 || mon3 < 0) {
                throw new IllegalArgumentException("Điểm không được âm");
            }

            ThiSinh thiSinh = new ThiSinh(maThiSinh, hoVaTen, tinh, ngaySinhDate, gioiTinh, mon1, mon2, mon3);

            List<ThiSinh> list = qlsvModel.getDsThiSinh();
            list.remove(thiSinh);
            qlsvModel.setDsThiSinh(list);
            xoaForm();
        }else {
            return;
        }
    }

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this ,"Không biết làm gì");
    }

    private void jButtonHuyBoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        xoaForm();
    }
    private int i = 1;
    public void addTable(){
        ThiSinh thíSinh = qlsvModel.getDsThiSinh().get(qlsvModel.size() - 1);

        // Định dạng cho đầu ra
        SimpleDateFormat sdfOutput = new SimpleDateFormat("dd/MM/yyyy");

        // Chuyển đối tượng Date thành chuỗi định dạng mới
        String ngaySinhFormatted = sdfOutput.format(thíSinh.getNgaySinh() );

        String gioiTinh = thíSinh.getGioiTinh().equals(true)?"Nam":"Nữ";
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
                i++ ,thíSinh.getMaThiSinh() ,thíSinh.getTenSinhVien() ,thíSinh.getQueQuan() ,ngaySinhFormatted,gioiTinh ,thíSinh.getDiemMon1() ,thíSinh.getDiemMon2() ,thíSinh.getDiemMon3()});
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSVView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonCapNhat;
    private javax.swing.JButton jButtonHuyBo;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTim;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboBoxQueQuan;
    private javax.swing.JComboBox<String> jComboBoxQueQuan1;
    private javax.swing.JLabel jLabeThongTinThiSinh;
    private javax.swing.JLabel jLabelDanhSachThiSinh1;
    private javax.swing.JLabel jLabelGioiTinh;
    private javax.swing.JLabel jLabelHoVaTen;
    private javax.swing.JLabel jLabelMaThiSinh;
    private javax.swing.JLabel jLabelMaThiSinh3;
    private javax.swing.JLabel jLabelMon1;
    private javax.swing.JLabel jLabelMon2;
    private javax.swing.JLabel jLabelMon3;
    private javax.swing.JLabel jLabelNgaySinh;
    private javax.swing.JLabel jLabelQueQuan1;
    private javax.swing.JLabel jLabelQueQuan2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonGioiTinhNam;
    private javax.swing.JRadioButton jRadioButtonGioiTinhNu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldHoVaTen1;
    private javax.swing.JTextField jTextFieldMaThiSinh1;
    private javax.swing.JTextField jTextFieldMaThiSinh2;
    private javax.swing.JTextField jTextFieldMon1;
    private javax.swing.JTextField jTextFieldMon2;
    private javax.swing.JTextField jTextFieldMon3;
    private javax.swing.JTextField jTextFieldNgaySinh;
    private javax.swing.JMenuItem menuClose;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.ButtonGroup jButtonGroupGioiTinh;

    // End of variables declaration
}
